name: blood_donation_app_full
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  permission_handler: ^11.3.1
  riverpod: ^3.0.3
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true