// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF10ORL37urJCO4zgdI2NcIdM6IYE-MSI',
    appId: '1:1040724245225:web:71564291d84ab851c60e78',
    messagingSenderId: '1040724245225',
    projectId: 'blood-donation-app-db5fe',
    authDomain: 'blood-donation-app-db5fe.firebaseapp.com',
    storageBucket: 'blood-donation-app-db5fe.firebasestorage.app',
    measurementId: 'G-1REZ9332YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofhs0tnv9tinDqf0skMRHjwX62Eb-Ui0',
    appId: '1:1040724245225:android:be41a7926ed591fdc60e78',
    messagingSenderId: '1040724245225',
    projectId: 'blood-donation-app-db5fe',
    storageBucket: 'blood-donation-app-db5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxfaAKvNCJiWJm8xWRKUE4ydzK0QyDxAs',
    appId: '1:1040724245225:ios:30a6160934b1f740c60e78',
    messagingSenderId: '1040724245225',
    projectId: 'blood-donation-app-db5fe',
    storageBucket: 'blood-donation-app-db5fe.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationAppFull',
  );
}
